### ISSUE TITLE
Add lang="typescript" to .svelte files

### ISSUE THREAD

**Issue by benmccann** [Zimtir/SENT-template#2]
See here for a template that does it: https://github.com/babichjacob/sapper-typescript-graphql-template

**Comment by Zimtir** [comment]
@benmccann could you please describe a reasons to use lang-property?
Because SENT-template by default supports typescript and javascript or I have mistake?

**Comment by benmccann** [comment]
The lang property is necessary to use Typescript in the templates. I thought the templates should use Typescript since this project is supposed to demonstrate how to use Typescript

**Comment by Zimtir** [comment]
@benmccann could you make acceptance criteria?

**Comment by benmccann** [comment]
Oh, I just noticed you're not using the official preprocessor. I had assumed you would be

With the latest version you can set the language just once in the config instead of setting it in each template. https://github.com/sveltejs/svelte-preprocess/blob/master/docs/getting-started.md#31-setting-default-languages

But anyway this would only makes sense if using the official preprocessor
