### ISSUE TITLE
Duplicate css styles

### ISSUE THREAD

**Issue by yroc92** [Zimtir/SENT-template#49]
When running in dev mode, rollup seems to be generating duplicate css styles for all the components. See attached screenshot

![image](https://user-images.githubusercontent.com/17517541/89744081-713fa980-da5e-11ea-805d-65d4f057e52a.png)

**Comment by babichjacob** [comment]
See upstream issue https://github.com/sveltejs/sapper/issues/1397

**Comment by Zimtir** [comment]
@yroc92 actually do you have this issue?

**Comment by yroc92** [comment]
I think this is a duplicate of sveltejs/sapper#1397.
