### ISSUE TITLE
Cannot read src/tsconfig.json

### ISSUE THREAD

**Issue by lamualfa** [Zimtir/SENT-template#50]
## Problem

Because `src` folder have `node_modules` folder within, Eslint always search for `tsconfig.json` in the `src` folder, not in the `root` folder. Because the Eslint cannot find the `tsconfig.json` in the `src` folder, the code editor always gives an error in the `import` syntax in every `.ts` file in the `src` folder. The error is:

![Screenshot from 2020-08-13 11-41-38](https://user-images.githubusercontent.com/39755201/90095175-1954bb80-dd5a-11ea-8aba-f10870ce6f29.png)

## My Environment

- Debian 10 buster
- VScode `v1.47.3`
- VScode Eslint Extension `v2.1.8`

**Comment by Zimtir** [comment]
Does it make sense to use .code-workspace?
You can open a workspace through VS Code (https://github.com/Zimtir/SENT-template/blob/master/template.code-workspace)

It can just hide unused files and directories

**Comment by lamualfa** [comment]
Thank's
