### ISSUE TITLE
Preload function not called in context="module" scripts

### ISSUE THREAD

**Issue by yroc92** [Zimtir/SENT-template#61]
As the title describes. I'm using the template but the `preload` in a svelte component is never called. Example:

```
<script context="module">
  console.log('in module') // this gets called
  export function preload(page, session) {
    console.log('session', session) // this never does
    return {
      foo: session.bar
    }
  }
</script>

<script lang="ts">
  export let foo;
</script>

<p>{foo}</p>
```

**Comment by Zimtir** [comment]
What directory of your component?

You can use "preload" only at **routes** (https://github.com/Zimtir/SENT-template/tree/master/src/routes) folder

Checkout official documentation here:

https://sapper.svelte.dev/docs#Routing
https://sapper.svelte.dev/docs#Preloading

It would be documented later at docs for this repository too,
Thank you for your feedback!

**Comment by Zimtir** [comment]
@yroc92 do you have any issues with it actually?
